/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as LinksIndexRouteImport } from './routes/links.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as SupportTicketIdRouteImport } from './routes/support.$ticketId'
import { Route as ServiceSummaryRouteImport } from './routes/service_.summary'
import { Route as ServiceNewRouteImport } from './routes/service_.new'
import { Route as ServiceRequestIdRouteImport } from './routes/service_.$requestId'
import { Route as ProjectsNewRouteImport } from './routes/projects_.new'
import { Route as ProjectsIdRouteImport } from './routes/projects_.$id'
import { Route as ProductsImportRouteImport } from './routes/products_.import'
import { Route as LinksCreateRouteImport } from './routes/links.create'
import { Route as LinksIdRouteImport } from './routes/links.$id'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as FormsSlugRouteImport } from './routes/forms.$slug'
import { Route as EmployeesNewRouteImport } from './routes/employees_.new'
import { Route as EmployeesAttendanceRouteImport } from './routes/employees_.attendance'
import { Route as EmployeesIdRouteImport } from './routes/employees_.$id'
import { Route as CustomersImportRouteImport } from './routes/customers_.import'
import { Route as CustomersIdRouteImport } from './routes/customers_.$id'
import { Route as AssetsSettingsRouteImport } from './routes/assets_.settings'
import { Route as AssetsNewRouteImport } from './routes/assets_.new'
import { Route as AssetsImportRouteImport } from './routes/assets_.import'
import { Route as AssetsIdRouteImport } from './routes/assets_.$id'
import { Route as AdminFeedbackRouteImport } from './routes/admin_.feedback'
import { Route as AdminFeedbackIndexRouteImport } from './routes/admin_.feedback.index'
import { Route as EmployeesAttendanceLogsRouteImport } from './routes/employees_.attendance_.logs'
import { Route as AdminOrganizationsIdRouteImport } from './routes/admin_.organizations.$id'
import { Route as AdminFeedbackIdRouteImport } from './routes/admin_.feedback.$id'
import { Route as ProjectsIdTasksTaskIdRouteImport } from './routes/projects_.$id_.tasks.$taskId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const LinksIndexRoute = LinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LinksRoute,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormsRoute,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => SupportRoute,
} as any)
const ServiceSummaryRoute = ServiceSummaryRouteImport.update({
  id: '/service_/summary',
  path: '/service/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceNewRoute = ServiceNewRouteImport.update({
  id: '/service_/new',
  path: '/service/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestIdRoute = ServiceRequestIdRouteImport.update({
  id: '/service_/$requestId',
  path: '/service/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects_/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsImportRoute = ProductsImportRouteImport.update({
  id: '/products_/import',
  path: '/products/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksCreateRoute = LinksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LinksRoute,
} as any)
const LinksIdRoute = LinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LinksRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSlugRoute = FormsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FormsRoute,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/employees_/new',
  path: '/employees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesAttendanceRoute = EmployeesAttendanceRouteImport.update({
  id: '/employees_/attendance',
  path: '/employees/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/employees_/$id',
  path: '/employees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersImportRoute = CustomersImportRouteImport.update({
  id: '/customers_/import',
  path: '/customers/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSettingsRoute = AssetsSettingsRouteImport.update({
  id: '/assets_/settings',
  path: '/assets/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsNewRoute = AssetsNewRouteImport.update({
  id: '/assets_/new',
  path: '/assets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsImportRoute = AssetsImportRouteImport.update({
  id: '/assets_/import',
  path: '/assets/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/assets_/$id',
  path: '/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin_/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackIndexRoute = AdminFeedbackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFeedbackRoute,
} as any)
const EmployeesAttendanceLogsRoute = EmployeesAttendanceLogsRouteImport.update({
  id: '/employees_/attendance_/logs',
  path: '/employees/attendance/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsIdRoute = AdminOrganizationsIdRouteImport.update({
  id: '/admin_/organizations/$id',
  path: '/admin/organizations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackIdRoute = AdminFeedbackIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFeedbackRoute,
} as any)
const ProjectsIdTasksTaskIdRoute = ProjectsIdTasksTaskIdRouteImport.update({
  id: '/projects_/$id_/tasks/$taskId',
  path: '/projects/$id/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/customers': typeof CustomersRoute
  '/drive': typeof DriveRoute
  '/emails': typeof EmailsRoute
  '/employees': typeof EmployeesRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forms': typeof FormsRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/links': typeof LinksRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/receivables': typeof ReceivablesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/support': typeof SupportRouteWithChildren
  '/admin/feedback': typeof AdminFeedbackRouteWithChildren
  '/assets/$id': typeof AssetsIdRoute
  '/assets/import': typeof AssetsImportRoute
  '/assets/new': typeof AssetsNewRoute
  '/assets/settings': typeof AssetsSettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/import': typeof CustomersImportRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/employees/attendance': typeof EmployeesAttendanceRoute
  '/employees/new': typeof EmployeesNewRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/links/$id': typeof LinksIdRoute
  '/links/create': typeof LinksCreateRoute
  '/products/import': typeof ProductsImportRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/service/$requestId': typeof ServiceRequestIdRoute
  '/service/new': typeof ServiceNewRoute
  '/service/summary': typeof ServiceSummaryRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/forms/': typeof FormsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/links/': typeof LinksIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/feedback/$id': typeof AdminFeedbackIdRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
  '/employees/attendance/logs': typeof EmployeesAttendanceLogsRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/projects/$id/tasks/$taskId': typeof ProjectsIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/customers': typeof CustomersRoute
  '/drive': typeof DriveRoute
  '/emails': typeof EmailsRoute
  '/employees': typeof EmployeesRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/receivables': typeof ReceivablesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets/import': typeof AssetsImportRoute
  '/assets/new': typeof AssetsNewRoute
  '/assets/settings': typeof AssetsSettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/import': typeof CustomersImportRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/employees/attendance': typeof EmployeesAttendanceRoute
  '/employees/new': typeof EmployeesNewRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/links/$id': typeof LinksIdRoute
  '/links/create': typeof LinksCreateRoute
  '/products/import': typeof ProductsImportRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/service/$requestId': typeof ServiceRequestIdRoute
  '/service/new': typeof ServiceNewRoute
  '/service/summary': typeof ServiceSummaryRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/forms': typeof FormsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/links': typeof LinksIndexRoute
  '/support': typeof SupportIndexRoute
  '/admin/feedback/$id': typeof AdminFeedbackIdRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
  '/employees/attendance/logs': typeof EmployeesAttendanceLogsRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/projects/$id/tasks/$taskId': typeof ProjectsIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/customers': typeof CustomersRoute
  '/drive': typeof DriveRoute
  '/emails': typeof EmailsRoute
  '/employees': typeof EmployeesRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forms': typeof FormsRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/links': typeof LinksRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/receivables': typeof ReceivablesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/support': typeof SupportRouteWithChildren
  '/admin_/feedback': typeof AdminFeedbackRouteWithChildren
  '/assets_/$id': typeof AssetsIdRoute
  '/assets_/import': typeof AssetsImportRoute
  '/assets_/new': typeof AssetsNewRoute
  '/assets_/settings': typeof AssetsSettingsRoute
  '/customers_/$id': typeof CustomersIdRoute
  '/customers_/import': typeof CustomersImportRoute
  '/employees_/$id': typeof EmployeesIdRoute
  '/employees_/attendance': typeof EmployeesAttendanceRoute
  '/employees_/new': typeof EmployeesNewRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/links/$id': typeof LinksIdRoute
  '/links/create': typeof LinksCreateRoute
  '/products_/import': typeof ProductsImportRoute
  '/projects_/$id': typeof ProjectsIdRoute
  '/projects_/new': typeof ProjectsNewRoute
  '/service_/$requestId': typeof ServiceRequestIdRoute
  '/service_/new': typeof ServiceNewRoute
  '/service_/summary': typeof ServiceSummaryRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/forms/': typeof FormsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/links/': typeof LinksIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin_/feedback/$id': typeof AdminFeedbackIdRoute
  '/admin_/organizations/$id': typeof AdminOrganizationsIdRoute
  '/employees_/attendance_/logs': typeof EmployeesAttendanceLogsRoute
  '/admin_/feedback/': typeof AdminFeedbackIndexRoute
  '/projects_/$id_/tasks/$taskId': typeof ProjectsIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assets'
    | '/chat'
    | '/customers'
    | '/drive'
    | '/emails'
    | '/employees'
    | '/feedback'
    | '/forgot-password'
    | '/forms'
    | '/invoices'
    | '/links'
    | '/login'
    | '/orders'
    | '/products'
    | '/projects'
    | '/receivables'
    | '/register'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/service'
    | '/settings'
    | '/stats'
    | '/support'
    | '/admin/feedback'
    | '/assets/$id'
    | '/assets/import'
    | '/assets/new'
    | '/assets/settings'
    | '/customers/$id'
    | '/customers/import'
    | '/employees/$id'
    | '/employees/attendance'
    | '/employees/new'
    | '/forms/$slug'
    | '/invite/$token'
    | '/invoices/$id'
    | '/invoices/new'
    | '/links/$id'
    | '/links/create'
    | '/products/import'
    | '/projects/$id'
    | '/projects/new'
    | '/service/$requestId'
    | '/service/new'
    | '/service/summary'
    | '/support/$ticketId'
    | '/forms/'
    | '/invoices/'
    | '/links/'
    | '/support/'
    | '/admin/feedback/$id'
    | '/admin/organizations/$id'
    | '/employees/attendance/logs'
    | '/admin/feedback/'
    | '/projects/$id/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assets'
    | '/chat'
    | '/customers'
    | '/drive'
    | '/emails'
    | '/employees'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/products'
    | '/projects'
    | '/receivables'
    | '/register'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/service'
    | '/settings'
    | '/stats'
    | '/assets/$id'
    | '/assets/import'
    | '/assets/new'
    | '/assets/settings'
    | '/customers/$id'
    | '/customers/import'
    | '/employees/$id'
    | '/employees/attendance'
    | '/employees/new'
    | '/forms/$slug'
    | '/invite/$token'
    | '/invoices/$id'
    | '/invoices/new'
    | '/links/$id'
    | '/links/create'
    | '/products/import'
    | '/projects/$id'
    | '/projects/new'
    | '/service/$requestId'
    | '/service/new'
    | '/service/summary'
    | '/support/$ticketId'
    | '/forms'
    | '/invoices'
    | '/links'
    | '/support'
    | '/admin/feedback/$id'
    | '/admin/organizations/$id'
    | '/employees/attendance/logs'
    | '/admin/feedback'
    | '/projects/$id/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assets'
    | '/chat'
    | '/customers'
    | '/drive'
    | '/emails'
    | '/employees'
    | '/feedback'
    | '/forgot-password'
    | '/forms'
    | '/invoices'
    | '/links'
    | '/login'
    | '/orders'
    | '/products'
    | '/projects'
    | '/receivables'
    | '/register'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/service'
    | '/settings'
    | '/stats'
    | '/support'
    | '/admin_/feedback'
    | '/assets_/$id'
    | '/assets_/import'
    | '/assets_/new'
    | '/assets_/settings'
    | '/customers_/$id'
    | '/customers_/import'
    | '/employees_/$id'
    | '/employees_/attendance'
    | '/employees_/new'
    | '/forms/$slug'
    | '/invite/$token'
    | '/invoices/$id'
    | '/invoices/new'
    | '/links/$id'
    | '/links/create'
    | '/products_/import'
    | '/projects_/$id'
    | '/projects_/new'
    | '/service_/$requestId'
    | '/service_/new'
    | '/service_/summary'
    | '/support/$ticketId'
    | '/forms/'
    | '/invoices/'
    | '/links/'
    | '/support/'
    | '/admin_/feedback/$id'
    | '/admin_/organizations/$id'
    | '/employees_/attendance_/logs'
    | '/admin_/feedback/'
    | '/projects_/$id_/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssetsRoute: typeof AssetsRoute
  ChatRoute: typeof ChatRoute
  CustomersRoute: typeof CustomersRoute
  DriveRoute: typeof DriveRoute
  EmailsRoute: typeof EmailsRoute
  EmployeesRoute: typeof EmployeesRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FormsRoute: typeof FormsRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LinksRoute: typeof LinksRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  ReceivablesRoute: typeof ReceivablesRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RfqRoute: typeof RfqRoute
  SearchRoute: typeof SearchRoute
  ServiceRoute: typeof ServiceRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  SupportRoute: typeof SupportRouteWithChildren
  AdminFeedbackRoute: typeof AdminFeedbackRouteWithChildren
  AssetsIdRoute: typeof AssetsIdRoute
  AssetsImportRoute: typeof AssetsImportRoute
  AssetsNewRoute: typeof AssetsNewRoute
  AssetsSettingsRoute: typeof AssetsSettingsRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersImportRoute: typeof CustomersImportRoute
  EmployeesIdRoute: typeof EmployeesIdRoute
  EmployeesAttendanceRoute: typeof EmployeesAttendanceRoute
  EmployeesNewRoute: typeof EmployeesNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ProductsImportRoute: typeof ProductsImportRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ServiceRequestIdRoute: typeof ServiceRequestIdRoute
  ServiceNewRoute: typeof ServiceNewRoute
  ServiceSummaryRoute: typeof ServiceSummaryRoute
  AdminOrganizationsIdRoute: typeof AdminOrganizationsIdRoute
  EmployeesAttendanceLogsRoute: typeof EmployeesAttendanceLogsRoute
  ProjectsIdTasksTaskIdRoute: typeof ProjectsIdTasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/links/': {
      id: '/links/'
      path: '/'
      fullPath: '/links/'
      preLoaderRoute: typeof LinksIndexRouteImport
      parentRoute: typeof LinksRoute
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/forms/': {
      id: '/forms/'
      path: '/'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof FormsRoute
    }
    '/support/$ticketId': {
      id: '/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof SupportRoute
    }
    '/service_/summary': {
      id: '/service_/summary'
      path: '/service/summary'
      fullPath: '/service/summary'
      preLoaderRoute: typeof ServiceSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service_/new': {
      id: '/service_/new'
      path: '/service/new'
      fullPath: '/service/new'
      preLoaderRoute: typeof ServiceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service_/$requestId': {
      id: '/service_/$requestId'
      path: '/service/$requestId'
      fullPath: '/service/$requestId'
      preLoaderRoute: typeof ServiceRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/new': {
      id: '/projects_/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$id': {
      id: '/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/import': {
      id: '/products_/import'
      path: '/products/import'
      fullPath: '/products/import'
      preLoaderRoute: typeof ProductsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/create': {
      id: '/links/create'
      path: '/create'
      fullPath: '/links/create'
      preLoaderRoute: typeof LinksCreateRouteImport
      parentRoute: typeof LinksRoute
    }
    '/links/$id': {
      id: '/links/$id'
      path: '/$id'
      fullPath: '/links/$id'
      preLoaderRoute: typeof LinksIdRouteImport
      parentRoute: typeof LinksRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$slug': {
      id: '/forms/$slug'
      path: '/$slug'
      fullPath: '/forms/$slug'
      preLoaderRoute: typeof FormsSlugRouteImport
      parentRoute: typeof FormsRoute
    }
    '/employees_/new': {
      id: '/employees_/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees_/attendance': {
      id: '/employees_/attendance'
      path: '/employees/attendance'
      fullPath: '/employees/attendance'
      preLoaderRoute: typeof EmployeesAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees_/$id': {
      id: '/employees_/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/import': {
      id: '/customers_/import'
      path: '/customers/import'
      fullPath: '/customers/import'
      preLoaderRoute: typeof CustomersImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/$id': {
      id: '/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets_/settings': {
      id: '/assets_/settings'
      path: '/assets/settings'
      fullPath: '/assets/settings'
      preLoaderRoute: typeof AssetsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets_/new': {
      id: '/assets_/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets_/import': {
      id: '/assets_/import'
      path: '/assets/import'
      fullPath: '/assets/import'
      preLoaderRoute: typeof AssetsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets_/$id': {
      id: '/assets_/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/feedback': {
      id: '/admin_/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/feedback/': {
      id: '/admin_/feedback/'
      path: '/'
      fullPath: '/admin/feedback/'
      preLoaderRoute: typeof AdminFeedbackIndexRouteImport
      parentRoute: typeof AdminFeedbackRoute
    }
    '/employees_/attendance_/logs': {
      id: '/employees_/attendance_/logs'
      path: '/employees/attendance/logs'
      fullPath: '/employees/attendance/logs'
      preLoaderRoute: typeof EmployeesAttendanceLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/organizations/$id': {
      id: '/admin_/organizations/$id'
      path: '/admin/organizations/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AdminOrganizationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/feedback/$id': {
      id: '/admin_/feedback/$id'
      path: '/$id'
      fullPath: '/admin/feedback/$id'
      preLoaderRoute: typeof AdminFeedbackIdRouteImport
      parentRoute: typeof AdminFeedbackRoute
    }
    '/projects_/$id_/tasks/$taskId': {
      id: '/projects_/$id_/tasks/$taskId'
      path: '/projects/$id/tasks/$taskId'
      fullPath: '/projects/$id/tasks/$taskId'
      preLoaderRoute: typeof ProjectsIdTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FormsRouteChildren {
  FormsSlugRoute: typeof FormsSlugRoute
  FormsIndexRoute: typeof FormsIndexRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsSlugRoute: FormsSlugRoute,
  FormsIndexRoute: FormsIndexRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface LinksRouteChildren {
  LinksIdRoute: typeof LinksIdRoute
  LinksCreateRoute: typeof LinksCreateRoute
  LinksIndexRoute: typeof LinksIndexRoute
}

const LinksRouteChildren: LinksRouteChildren = {
  LinksIdRoute: LinksIdRoute,
  LinksCreateRoute: LinksCreateRoute,
  LinksIndexRoute: LinksIndexRoute,
}

const LinksRouteWithChildren = LinksRoute._addFileChildren(LinksRouteChildren)

interface SupportRouteChildren {
  SupportTicketIdRoute: typeof SupportTicketIdRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportTicketIdRoute: SupportTicketIdRoute,
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface AdminFeedbackRouteChildren {
  AdminFeedbackIdRoute: typeof AdminFeedbackIdRoute
  AdminFeedbackIndexRoute: typeof AdminFeedbackIndexRoute
}

const AdminFeedbackRouteChildren: AdminFeedbackRouteChildren = {
  AdminFeedbackIdRoute: AdminFeedbackIdRoute,
  AdminFeedbackIndexRoute: AdminFeedbackIndexRoute,
}

const AdminFeedbackRouteWithChildren = AdminFeedbackRoute._addFileChildren(
  AdminFeedbackRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssetsRoute: AssetsRoute,
  ChatRoute: ChatRoute,
  CustomersRoute: CustomersRoute,
  DriveRoute: DriveRoute,
  EmailsRoute: EmailsRoute,
  EmployeesRoute: EmployeesRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FormsRoute: FormsRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  LinksRoute: LinksRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  ReceivablesRoute: ReceivablesRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RfqRoute: RfqRoute,
  SearchRoute: SearchRoute,
  ServiceRoute: ServiceRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  SupportRoute: SupportRouteWithChildren,
  AdminFeedbackRoute: AdminFeedbackRouteWithChildren,
  AssetsIdRoute: AssetsIdRoute,
  AssetsImportRoute: AssetsImportRoute,
  AssetsNewRoute: AssetsNewRoute,
  AssetsSettingsRoute: AssetsSettingsRoute,
  CustomersIdRoute: CustomersIdRoute,
  CustomersImportRoute: CustomersImportRoute,
  EmployeesIdRoute: EmployeesIdRoute,
  EmployeesAttendanceRoute: EmployeesAttendanceRoute,
  EmployeesNewRoute: EmployeesNewRoute,
  InviteTokenRoute: InviteTokenRoute,
  ProductsImportRoute: ProductsImportRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ServiceRequestIdRoute: ServiceRequestIdRoute,
  ServiceNewRoute: ServiceNewRoute,
  ServiceSummaryRoute: ServiceSummaryRoute,
  AdminOrganizationsIdRoute: AdminOrganizationsIdRoute,
  EmployeesAttendanceLogsRoute: EmployeesAttendanceLogsRoute,
  ProjectsIdTasksTaskIdRoute: ProjectsIdTasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
