/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinksIndexRouteImport } from './routes/links.index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as LinksCreateRouteImport } from './routes/links.create'
import { Route as LinksIdRouteImport } from './routes/links.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as FormsSlugRouteImport } from './routes/forms.$slug'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksIndexRoute = LinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LinksRoute,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormsRoute,
} as any)
const LinksCreateRoute = LinksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LinksRoute,
} as any)
const LinksIdRoute = LinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LinksRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSlugRoute = FormsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FormsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/emails': typeof EmailsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forms': typeof FormsRouteWithChildren
  '/links': typeof LinksRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/links/$id': typeof LinksIdRoute
  '/links/create': typeof LinksCreateRoute
  '/forms/': typeof FormsIndexRoute
  '/links/': typeof LinksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/emails': typeof EmailsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/links/$id': typeof LinksIdRoute
  '/links/create': typeof LinksCreateRoute
  '/forms': typeof FormsIndexRoute
  '/links': typeof LinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/emails': typeof EmailsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forms': typeof FormsRouteWithChildren
  '/links': typeof LinksRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/links/$id': typeof LinksIdRoute
  '/links/create': typeof LinksCreateRoute
  '/forms/': typeof FormsIndexRoute
  '/links/': typeof LinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/emails'
    | '/forgot-password'
    | '/forms'
    | '/links'
    | '/login'
    | '/products'
    | '/register'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/settings'
    | '/stats'
    | '/forms/$slug'
    | '/invite/$token'
    | '/links/$id'
    | '/links/create'
    | '/forms/'
    | '/links/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/emails'
    | '/forgot-password'
    | '/login'
    | '/products'
    | '/register'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/settings'
    | '/stats'
    | '/forms/$slug'
    | '/invite/$token'
    | '/links/$id'
    | '/links/create'
    | '/forms'
    | '/links'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/emails'
    | '/forgot-password'
    | '/forms'
    | '/links'
    | '/login'
    | '/products'
    | '/register'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/settings'
    | '/stats'
    | '/forms/$slug'
    | '/invite/$token'
    | '/links/$id'
    | '/links/create'
    | '/forms/'
    | '/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  EmailsRoute: typeof EmailsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FormsRoute: typeof FormsRouteWithChildren
  LinksRoute: typeof LinksRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RfqRoute: typeof RfqRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/': {
      id: '/links/'
      path: '/'
      fullPath: '/links/'
      preLoaderRoute: typeof LinksIndexRouteImport
      parentRoute: typeof LinksRoute
    }
    '/forms/': {
      id: '/forms/'
      path: '/'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof FormsRoute
    }
    '/links/create': {
      id: '/links/create'
      path: '/create'
      fullPath: '/links/create'
      preLoaderRoute: typeof LinksCreateRouteImport
      parentRoute: typeof LinksRoute
    }
    '/links/$id': {
      id: '/links/$id'
      path: '/$id'
      fullPath: '/links/$id'
      preLoaderRoute: typeof LinksIdRouteImport
      parentRoute: typeof LinksRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$slug': {
      id: '/forms/$slug'
      path: '/$slug'
      fullPath: '/forms/$slug'
      preLoaderRoute: typeof FormsSlugRouteImport
      parentRoute: typeof FormsRoute
    }
  }
}

interface FormsRouteChildren {
  FormsSlugRoute: typeof FormsSlugRoute
  FormsIndexRoute: typeof FormsIndexRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsSlugRoute: FormsSlugRoute,
  FormsIndexRoute: FormsIndexRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface LinksRouteChildren {
  LinksIdRoute: typeof LinksIdRoute
  LinksCreateRoute: typeof LinksCreateRoute
  LinksIndexRoute: typeof LinksIndexRoute
}

const LinksRouteChildren: LinksRouteChildren = {
  LinksIdRoute: LinksIdRoute,
  LinksCreateRoute: LinksCreateRoute,
  LinksIndexRoute: LinksIndexRoute,
}

const LinksRouteWithChildren = LinksRoute._addFileChildren(LinksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  EmailsRoute: EmailsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FormsRoute: FormsRouteWithChildren,
  LinksRoute: LinksRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RfqRoute: RfqRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
